### ISSUE TITLE
Potential iPad Crashes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#206] opened 2021-12-02 21:56 UTC
For https://github.com/phetsims/qa/issues/745
When using `?showPointerAreas` on iPadOS 15, the sim crashed and reloaded after a few minutes of use. It also did it fairly quickly a second time (still with the parameter). I did see it again with `?stringTest=X`.
This type of crashing and reloading has been seen before on older iOSs and tended to be when the sim was using more resources. I also know that `?showPointerAreas` at least can decrease performance. The fact that it happened with `?stringTest=X` seems more odd to me.
I wasn't able to find any particular action that caused this. It could happen on the home screen or while rotating a molecule in the sim.

**Comment by stemilymill** [comment] 2021-12-06 20:32
I have been unable to reproduce this on iPad Pro with iPadOS 15.1

**Comment by jonathanolson** [comment] 2021-12-27 21:04
I have an iPad with iOS 9.3.5 which seems old enough that it's not loading (says "Your software is up to date."). Looks like an iPad 2 (Lave).

I'm curious if it's a memory issue, or possibly a GPU issue (dealing with 3d), or some other issue. To debug, I'd probably need to reproduce while tethered.

@kathy-phet thought on priority? I'd probably need an in-person device in order to reproduce/debug (I'm curious about what the limits on newer iPads are, so that we don't break this with future sims).

**Comment by arouinfar** [comment] 2022-10-07 18:14
@jonathanolson this issue seems a bit stale. Let's plan on asking QA to reproduce in the next dev test. If it's still an issue, we can discuss next steps.

**Comment by samreid** [comment] 2022-12-23 16:22
I tested a built version on iPad on iOS 15.6.1 with ?stringTest=x and used it for about 6 minutes, dragging molecules, creating molecules, tapping checkboxes, pinch to zoom, etc.  It did not crash and is still running nicely.  Closing for now, but please reopen or create a new issue if this recurs.

**Closed by samreid** 2022-12-23 16:22 UTC
Labels: type:bug, status:ready-for-review
