### ISSUE TITLE
Assertion errors appear when attempting to add checkbox to empty options panel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#235] opened 2022-10-27 13:53 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/845 and https://github.com/phetsims/qa/issues/844
In Studio: After setting checkbox visibleProperty to false for all checkboxes in the Options panel, attempting to change the visibleProperty back to true, results in assertion errors.

**Steps to reproduce**
In Basics:
1. In studio, select "all" under PhET-iO elements
2. Set `moleculeShapesBasics.modelScreen.view.optionsPanel.showBondAnglesCheckbox.visibleProperty` to false --The title 'Options' is still present on the screen
3. Try to set `moleculeShapesBasics.modelScreen.view.optionsPanel.showBondAnglesCheckbox.visibleProperty` to true --assertion errors appear

This also happens on the Real Molecules screen.

In full version of the sim:
Set both 'moleculeShapes.modelScreen.view.optionsPanel.showBondAnglesCheckbox.visibleProperty' and `moleculeShapes.modelScreen.view.optionsPanel.showLonePairsCheckbox.visibleProperty' to false. Then try and set one to true. 

**Visuals**
<img width="1078" alt="Screenshot 2022-10-27 at 9 13 17 AM" src="https://user-images.githubusercontent.com/87318828/198303087-ad4b070f-f111-4e24-8007-18a2e95daf27.png">

**Comment by Nancy-Salpepi** [comment] 2022-10-27 14:00
This error doesn't occur when I do something similar in the Name Panel but does happen with the Bonding Panel

**Comment by samreid** [comment] 2022-12-16 18:39
I was able to easily reproduce this problem. Looks like it is trying to set a negative preferred width for some reason.  I could likely come up with a working workaround, but may be better to get help from @jonathanolson or @marlitas about how to deal with that in the layout engine.

**Comment by jonathanolson** [comment] 2022-12-23 16:31
Commit should handle this above, closing. Thanks!

**Closed by jonathanolson** 2022-12-23 16:31 UTC
Labels: type:bug
