### ISSUE TITLE
ComboBox width does not appropriately scale

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#225] opened 2022-10-07 15:46 UTC
Related to #223 

When the Molecule panel expands to maintain width with the Options panel, the ComboBox ends up oddly stretched. The button is overly large and the ListBox width also appears to be too narrow.

![image](https://user-images.githubusercontent.com/8419308/194594530-d1997b05-cf32-4ab7-9c4b-9ce9373e65ce.png)

**Comment by arouinfar** [comment] 2022-10-20 18:39
Tagging for https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845.

**Comment by KatieWoe** [comment] 2022-10-21 19:29
Noting that this did not occur in the published version of the sim.
Dev version:
![now](https://user-images.githubusercontent.com/41024075/197274736-0223792e-6d7d-4762-9b06-3f54071f504f.png)
Published version:
![then](https://user-images.githubusercontent.com/41024075/197274786-7974e5e6-3371-4528-8b62-d4154159a38b.png)

**Comment by samreid** [comment] 2022-12-16 17:51
I'll take a look...

**Comment by samreid** [comment] 2022-12-16 17:53
We can shut off the resizing of the combo box like so:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/679486/208158923-2ec6504f-a5db-400d-998f-51db9f741ddd.png">

It wasn't clear from the issue comments whether that is the desired solution.  @arouinfar or @KatieWoe can you please review and close if all is well?

**Comment by KatieWoe** [comment] 2022-12-16 20:39
I'm not seeing the molecule box expand in master so I'm not sure how to check for this at the moment.
<img width="959" alt="notlonger" src="https://user-images.githubusercontent.com/41024075/208185182-8fa9acc0-a885-437f-bb35-65e1e94dcbd6.png">

**Comment by samreid** [comment] 2022-12-16 22:12
@arouinfar does this look ok to you?  (No longer stretching the combo box?)

**Comment by arouinfar** [comment] 2022-12-19 21:07
@samreid looks good to me. 

> I'm not seeing the molecule box expand in master so I'm not sure how to check for this at the moment.

Since the ComboBox contents (chemical formulas) aren't translatable and #224 hasn't been resolved yet, I tested it in a roundabout way. Increasing the width of a checkbox label will cause the Options panel (and therefore the Molecule panel) to expand. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/8419308/208523636-7d94a917-d067-44bf-9e46-d93dfabc0bf6.png">

**Comment by Nancy-Salpepi** [comment] 2023-02-21 20:57
This issue still exists in https://github.com/phetsims/qa/issues/905. Reopening.
<img width="334" alt="Screenshot 2023-02-21 at 3 56 03 PM" src="https://user-images.githubusercontent.com/87318828/220456835-e657c5cb-c187-4f0b-96cf-49b40227e9e6.png">

**Comment by jonathanolson** [comment] 2023-02-22 04:47
Weirdly enough, I think my fix for https://github.com/phetsims/molecule-shapes/issues/242 also applies here (handles resizing of content in those "titled" panels). I can't reproduce this in master. @Nancy-Salpepi are you able to reproduce this in master?

**Comment by Nancy-Salpepi** [comment] 2023-02-22 14:44
This looks good in master now, with the fix from https://github.com/phetsims/molecule-shapes/issues/242 (even though that issue is still present)

**Comment by jonathanolson** [comment] 2023-03-02 23:04
Please close after verifying!

**Comment by Nancy-Salpepi** [comment] 2023-03-03 01:51
This is fixed in the PhET brand sim and in a Standard wrapper, but is broken in the Studio wrapper.  The combobox doesn't shift when the panel resizes as I change locales. 

<img width="322" alt="Screenshot 2023-03-02 at 8 43 55 PM" src="https://user-images.githubusercontent.com/87318828/222610449-d3d5b637-34a0-4d4a-a2d4-88608615425e.png">

**Comment by jonathanolson** [comment] 2023-03-07 21:19
I believe this is fixed in master. @Nancy-Salpepi can you verify?

@zepumph can you complete review of https://github.com/phetsims/sun/commit/b7f1be274e36b1430cc9b55f5611197f31b7a1e0 and https://github.com/phetsims/scenery/commit/cfa90b858bfdfdfb11b3221b36a8ad4cf6076082?

Also leaving assigned to myself for creation of unit tests (there's a lot to verify, and I haven't tested cases where one node is an ancestor of another).

**Comment by Nancy-Salpepi** [comment] 2023-03-07 21:52
This looks good in master!

**Comment by zepumph** [comment] 2023-03-08 00:06
Looks great. Thanks @jonathanolson!

**Comment by jonathanolson** [comment] 2023-03-08 01:21
> would it be more performant for below opperations if these were Sets?

I don't believe it would be significantly so at all. This also isn't written with being highly performant for node changes (it already requires a lot of machinery, and I'm trying to keep it simple and readable), so a lot of the closures that are created are probably higher overhead.

**Comment by KatieWoe** [comment] 2023-03-08 20:32
Looks good in rc.3

**Closed by KatieWoe** 2023-03-08 20:32 UTC
Labels: dev:phet-io, status:fixed-awaiting-deploy
