### ISSUE TITLE
Molecule sometimes vibrates after being rotated

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#203] opened 2021-11-29 17:38 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Seen on both Safari and Chrome

**Problem description**
https://github.com/phetsims/qa/issues/745

The SF4 molecule will sometimes begin to vibrate after being rotated. Not sure what triggers it. I have only seen it occur with this particular molecule and I have only seen it in the XHTML version. 

**Steps to reproduce**
1. In PhET Options select 'Projector Mode' and 'Show Outer Lone Pairs'
2. In the 'Real Molecules' screen, check the show bond angles checkbox.
2. Select SF4
3. Rotate and jiggle the molecule around --It will eventually start to vibrate in place.

**Visuals**
![moleculevibration3](https://user-images.githubusercontent.com/87318828/143916125-37d84b2b-5eeb-41ce-bbba-084da436a133.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-rc.1/phet/xhtml/molecule-shapes_all.xhtml
Version: 1.4.0-rc.1 2021-11-24 02:29:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
Language: en-US
Window: 1419x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by stemilymill** [comment] 2021-11-29 17:48
I was able to reproduce this on Win10 Chrome on both html and xhtml, but only with the SF4 molecule so far. I reproduced it with and without the outer lone pairs visible.

**Comment by Nancy-Salpepi** [comment] 2021-11-29 18:34
I was just able to reproduce in the sim version on Mac + safari without outer lone pairs.
![vibratesim](https://user-images.githubusercontent.com/87318828/143923477-24d0d27a-39e5-4aea-8d23-e2f5ee5023d0.gif)

**Comment by stemilymill** [comment] 2021-11-29 20:04
Just reproduced on published version

https://user-images.githubusercontent.com/85511101/143934154-f32e557a-7e6e-4194-9b8c-c8a0b4dc9435.mp4




<details><summary>Troubleshooting information:</summary>
<p>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html
Version: 1.2.10 2021-09-23 10:04:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Language: en-US
Window: 1418x656
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</p>
</details>

**Comment by jonathanolson** [comment] 2021-12-28 20:02
Reproducing with the following console input:

```js

phet.moleculeShapes.MoleculeShapesModel.MoleculeShapesModelIO.applyState( phet.joist.sim.screens[2].model, {"isReal":true,"groups":[{"position":{"x":1.4777645578082776,"y":-2.4417917816145622,"z":-6.391702809652939},"velocity":{"x":0.19180709238376514,"y":-0.3169334244507079,"z":-0.8296138412731942},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":11.792024954007255,"y":4.687454910402233,"z":-2.1497331657629033},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":5.781244252512414,"y":9.75211710406454,"z":6.153567171431913},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":3.0524093615642958,"y":11.548318211120442,"z":-4.805416868092824},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-12.42635430858548,"y":3.3177052857020164,"z":-0.7914708321150484},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-4.832283392794114,"y":11.828039384104322,"z":-1.6613426055618161},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-6.780747091154818,"y":6.915486220512522,"z":8.469581834564048},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0.3607087942123171,"y":-1.1126923472720693,"z":12.813609377900868},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":10.30555904765963,"y":1.1092415945031862,"z":7.647516302469863},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":5.661493244798237,"y":-9.315671846194746,"z":6.876570210227663},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-12.214196279195852,"y":-4.0907848953457755,"z":-0.03429442236285258},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-5.933145804800793,"y":-6.984185350422291,"z":9.075390705469168},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-4.158227776599913,"y":-12.137042050784649,"z":-0.972912571206098},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"S","isCentralAtom":true},{"position":{"x":-5.868621836874141,"y":-6.106421770520658,"z":2.1236687558359817},"velocity":{"x":-0.5504859720018791,"y":-0.7315640898961715,"z":-0.03447780768917329},"isLonePair":false,"element":"F","isCentralAtom":false},{"position":{"x":4.294054039275067,"y":-2.4502523433813406,"z":7.1926283900229535},"velocity":{"x":0.32722969507056265,"y":-0.21931927720123512,"z":0.36730480232340984},"isLonePair":false,"element":"F","isCentralAtom":false},{"position":{"x":-6.323388861285905,"y":5.803434055818369,"z":1.5847543229653618},"velocity":{"x":-0.4073669177636259,"y":0.3517344246206486,"z":-0.020691190067912646},"isLonePair":false,"element":"F","isCentralAtom":false},{"position":{"x":5.426155579766522,"y":6.837533140419486,"z":-0.20989108145064306},"velocity":{"x":0.6224567505395916,"y":0.6126428080037198,"z":-0.27681388283198793},"isLonePair":false,"element":"F","isCentralAtom":false}],"bonds":[{"a":0,"b":13,"order":0,"length":7},{"a":1,"b":17,"order":0,"length":7.000000000000004},{"a":2,"b":17,"order":0,"length":7.000000000000002},{"a":3,"b":17,"order":0,"length":7.000000000000002},{"a":4,"b":16,"order":0,"length":7.000000000000002},{"a":5,"b":16,"order":0,"length":7.000000000000003},{"a":6,"b":16,"order":0,"length":7.000000000000001},{"a":7,"b":15,"order":0,"length":6.999999999999998},{"a":8,"b":15,"order":0,"length":7.000000000000001},{"a":9,"b":15,"order":0,"length":6.999999999999998},{"a":10,"b":14,"order":0,"length":7},{"a":11,"b":14,"order":0,"length":6.999999999999998},{"a":12,"b":14,"order":0,"length":6.999999999999999},{"a":14,"b":13,"order":1,"length":8.772499999999999},{"a":15,"b":13,"order":1,"length":8.772499999999999},{"a":16,"b":13,"order":1,"length":8.772499999999999},{"a":17,"b":13,"order":1,"length":8.772499999999999}],"lastMidpoint":null,"realMoleculeShape":{"displayName":"SF4"},"bondLengthOverride":null,"realMoleculeShape":{"displayName":"SF4"},"showRealView":true})
```

**Comment by jonathanolson** [comment] 2022-01-20 03:36
This should finally be fixed up, can you verify?

**Comment by Nancy-Salpepi** [comment] 2022-01-22 14:36
Sorry @jonathanolson...was I supposed to close this issue?

**Comment by jonathanolson** [comment] 2022-01-22 23:22
Closing works for me, thanks!

**Closed by jonathanolson** 2022-01-22 23:22 UTC
Labels: type:bug
