### ISSUE TITLE
Sighting: Laggy/Freezing behavior on retina Macbook Pro 2015 15"

### ISSUE THREAD

**Issue by samreid** [phetsims/molecule-shapes#124] opened 2015-06-16 02:42 UTC
I tested Molecule Shapes 1.0.0 on a new in-store retina MacBook Pro 2015 15" with Iris Pro graphics.  After the sim started, when I tried to interact with the molecule, the sim froze for 15+ seconds.  I restarted safari and saw the same behavior, see movie:

https://www.youtube.com/watch?v=H0T9UbVMPfs

This problem was also exhibited in several (but not all) of the three.js examples.

After rebooting, the problem disappeared and the sim ran smoothly (at some 35 or so frames per second).

Perhaps this was a one-time glitch, but I thought I'd create an issue for it and we can have someone else test it out when we have the hardware.

**Comment by orejolaphet** [comment] 2015-07-21 17:18
@samreid 
Same behavior occurs on my machine on Safari 8.0.7 . The newer Macbook (10.10.4) 2015 12" 

I noticed that during the freeze that occurs after interacting with the molecule changing browser tab or change application and return to safari the molecule orients itself to a new position.

Troubleshooting information (do not edit):
Name: ‪Molecule Shapes‬
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.0-rc.1/molecule-shapes_en.html
Version: 1.1.0-rc.1 2015-07-20 18:55:19 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12
Language: en-us
Window: 1240x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.31)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"579f8c66","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"42896196","branch":"phet"},"chipper":{"sha":"d5bea1ca","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"a5de6c77","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"molecule-shapes":{"sha":"8a2784f4","branch":"1.1"},"nitroglycerin":{"sha":"c6f79ce4","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"24a4d9ab","branch":"master"},"scenery-phet":{"sha":"f3f30545","branch":"master"},"sherpa":{"sha":"fdc6e97a","branch":"master"},"sun":{"sha":"dc08e5f3","branch":"master"}}

**Comment by orejolaphet** [comment] 2015-07-21 17:22
Issue does not occur with downloaded file.

**Comment by samreid** [comment] 2015-07-21 17:43
I'll assign this to @jonathanolson to investigate, but he may need some additional hardware in order to reproduce/debug the problem.

**Comment by jonathanolson** [comment] 2015-07-23 18:56
Will investigate in person, but not sure there's much I can do to fix it.

**Comment by jonathanolson** [comment] 2015-08-04 19:23
I wasn't able to reproduce on Curie or Turing.

@ariel-phet, is this worth a trip to the Apple store to investigate? I'm not sure I have access to any other devices that have the OS/Hardware combination.

**Comment by oliver-phet** [comment] 2015-08-04 22:04
I was able to reproduce this behavior on my 13" MBPR. Will update with more info as it becomes available.

**Comment by oliver-phet** [comment] 2015-08-04 22:07
This was an error in the web inspector:
[Error] TypeError: undefined is not an object (evaluating 'safari.self.tab.dispatchMessage')
	send_focus (onloadwff.js, line 139)
	(anonymous function) (onloadwff.js, line 143)

**Comment by jonathanolson** [comment] 2015-08-13 20:14
Now can't reproduce on @oliver-phet's laptop. Since it seems hardware specific and random, and I feel like there is very likely nothing I could do to fix it even if we know more about the problem (I've googled about this a ton), I think it's worth marking as will-not-fix.

@ariel-phet, thoughts?

**Comment by jonathanolson** [comment] 2015-08-13 21:06
Closing as will-not-fix.

**Closed by jonathanolson** 2015-08-13 21:06 UTC
Labels: bug
