### ISSUE TITLE
Heavy Lag on iPad 7

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/molecule-shapes#128] opened 2015-07-21 18:11 UTC
Test device: iPad 2

Operating System: iOS 7.1

Browser: Safari

Problem description: WebGL is not enabled so Low Graphics Quality runs automatically. There is significant lag. Lone pairs often "jump" away from the molecule and freeze in space when the molecule is being dragged. Also occurs in iFrame.

Steps to reproduce: 

Severity:

Screenshots: 
![image 5](https://cloud.githubusercontent.com/assets/12610678/8808730/9fffceac-2fa1-11e5-9b4c-7d5302fea876.jpg)

Troubleshooting information (do not edit):
Name: ‪Molecule Shapes‬
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.0-rc.1/molecule-shapes_en.html?webgl=false
Version: 1.1.0-rc.1 2015-07-20 18:55:19 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: disabled
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"579f8c66","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"42896196","branch":"phet"},"chipper":{"sha":"d5bea1ca","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"a5de6c77","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"molecule-shapes":{"sha":"8a2784f4","branch":"1.1"},"nitroglycerin":{"sha":"c6f79ce4","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"24a4d9ab","branch":"master"},"scenery-phet":{"sha":"f3f30545","branch":"master"},"sherpa":{"sha":"fdc6e97a","branch":"master"},"sun":{"sha":"dc08e5f3","branch":"master"}}

**Comment by elisemorgan** [comment] 2015-07-21 18:27
Also seen in Win 7 w/ IE 10

**Comment by ariel-phet** [comment] 2015-07-23 15:22
@elisemorgan - this is a known issue. The low graphics quality is because these platforms do not support webgl (which allows us to render the smooth looking shapes).

For platforms that run with "low graphics quality" it is important that they still perform well, but it is OK if they have this very angular look (it is intentional). Please comment if you are seeing any performance issues (dragging not smooth etc), but the low graphics quality is not considered a problem.

**Comment by elisemorgan** [comment] 2015-07-24 16:52
@ariel-phet I've changed the name to better reflect the issue. There is a significant amount of lag on the iPad 7, as commented above. The molecule is unable to stay together while being dragged. Unfortunately I'm not sure how to do a recording of my screen on the iPad.

**Comment by jonathanolson** [comment] 2015-07-28 17:15
Tested with Lave (iOS 7.1 iPad 2) for ~10 minutes, and while it was slow (due to Canvas rendering), I wasn't able to get anything to separate or stay stuck (molecule was together). Seemed acceptable for what we can do on the device.

@ariel-phet, should we have more testing done to get reproduction instructions/video, or accept as-is?

**Comment by ariel-phet** [comment] 2015-07-28 18:22
App store is currently reporting 85% of devices are using iOS8. With iOS9 due in September and us likely dropping iOS7 support soon, I think we can leave as is. Closing.

**Closed by ariel-phet** 2015-07-28 18:22 UTC
