### ISSUE TITLE
Safari 7 performance w/ WebGL enabled

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecule-shapes#103] opened 2015-02-12 17:31 UTC
Test device: MacBook Pro

Operating System: OSX 10.9.5

Browser: Safari 7.1 (9537.85.10.17.1)

Problem description: Safari performance w/ WebGL enabled is quite sluggish

Steps to reproduce:
-make sure WebGL is enabled
-open sim
-open model tab
-remove all bonds
-quickly add as many bonds as you can
-the sim will become extremely sluggish and will take a while to load the new bonds.

if you can get the bonds to load immediately, dragging and moving the bonds will also be very sluggish and slow. Also enabling all other features (geometry, lone pairs, etc.) will cause the sim to have even slower performance. 

Severity: High

Screenshots:

Troubleshooting information (do not edit):
Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html
Version: 1.0.0-dev.15
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10
Language: en-us
Window: 1024x605
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.24.16)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jonathanolson** [comment] 2015-02-19 17:13
Testing on Magnus (OS X 10.9.5, Safari 7.1 (9537.85.10.17.1)), I'm not able to reproduce this issue (within ~10 minutes of testing). It seems quite smooth.

Did it happen on another device, or is there a better way of reproducing it?

**Comment by jonathanolson** [comment] 2015-03-01 01:25
@bryo5363 or @orejolaphet, please let me know if there is a way I can reproduce this in person (what specific device) so that I can look into profiling/fixing it if possible (since I see it in the test matrix).

**Comment by ariel-phet** [comment] 2015-05-20 22:02
The sim is published, and this seems no longer a concern, closing

**Closed by ariel-phet** 2015-05-20 22:02 UTC
