### ISSUE TITLE
Safari 6.1.6 (8537.78.2) w/ WebGL is very sluggish

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecule-shapes#104] opened 2015-02-12 18:32 UTC
Test device: MacBook Pro

Operating System: OSX 10.8.5

Browser: Safari 6.1.6

Problem description: Very sluggish performance

Steps to reproduce:
-open sim
-manipulate molecule. notice the sim processes very slowly
-click bond angles. There will not be a numerical readout of angles. 

Severity:

Screenshots:
![screen shot 2015-02-12 at 11 25 38 am](https://cloud.githubusercontent.com/assets/7717368/6174255/c4b5a27c-b2aa-11e4-9ca3-cad00137bfd8.png)

Troubleshooting information (do not edit):
Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html
Version: 1.0.0-dev.15
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2
Language: en-us
Window: 1280x596
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.16.74)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jonathanolson** [comment] 2015-02-19 17:19
Initial testing indicates the text isn't showing up due to the texture being treated as cross-domain.

Additionally I'm able to reproduce significant delays in-between clicks and seeing actions happen.

**Comment by jonathanolson** [comment] 2015-02-19 17:38
Performance profile indicates 65% CPU, with 44% total spent in the model steps. It looks like we're already doing as few Jacobi iterations as possible, so it will be difficult to improve. Will also check for out-of-animation-frame DOM updates.

**Comment by jonathanolson** [comment] 2015-02-19 17:40
Graphics profiling shows minimal time spent painting. Very doubtful that the view is the bottleneck.

**Comment by jonathanolson** [comment] 2015-02-19 17:42
Combined timeline shows paints between every animation frame as hoped, no extraneous paints, and animation frame CPU times that can reach 100ms.

**Comment by jonathanolson** [comment] 2015-02-19 18:46
Important performance:
```
65% animation frame
  44% model step
    33% applyAttraction
      18% computeRotationMatrixWithTranspose
        8% multRightTranspose
        10% svd3
          7% jacobiIteration3
      8% mult
    6% getLocalShape (vseprPermutations -> permuteListWithIndices)
  20% updateView
    16% three.js renderer
    3% updateView
```

**Comment by jonathanolson** [comment] 2015-02-19 18:49
The image URL constructed looks perfect, but WebGL in Safari 6.1 might not like data URLs (might require a raw Canvas).

**Comment by jonathanolson** [comment] 2015-03-18 03:27
Fixed the bond angle readout part of this.

**Comment by jonathanolson** [comment] 2015-08-04 19:24
Since the bond angle readout part is fixed, and we're not really supporting that browser, I'm closing this issue.

**Closed by jonathanolson** 2015-08-04 19:24 UTC
